"""`tech-news-digest init`: scaffold a new topic repo's config + workflows.

Run this *inside the repo you want the digest to live in* — typically via
`uvx --from "git+https://github.com/LPF9000/tech-news-digest.git@<ref>"
tech-news-digest init`, so nothing needs installing locally. It writes
three files, all pointed at the right engine repo and ref already:
`config/feeds.toml`, `.github/workflows/digest.yml` (the scheduled run),
and `.github/workflows/ci.yml` (lints workflows, validates the config,
and scans for leaked secrets on every push/PR). Only the topic content
(sources/categories/keywords) is left as placeholders for a human or an
AI agent to fill in.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

# Keep in sync with digest-reusable.yml's own `inputs.digest-ref.default`.
DEFAULT_ENGINE_REF = "main"

_GITHUB_REMOTE_RE = re.compile(r"github\.com[:/]([^/]+)/(.+?)(?:\.git)?/?$")

CONFIG_TEMPLATE = """\
# Source & topic configuration for your digest.
# Generated by `tech-news-digest init` — fill in the TODOs below, or hand
# this whole file plus a description of your topic to your AI coding
# agent (see the schema reference this command printed, also in
# https://github.com/LPF9000/tech-news-digest/blob/main/AGENTS.md).

# --- Top-level settings ---------------------------------------------------
# NOTE: top-level keys like these must stay above the first `[[...]]`
# array-of-tables header below — TOML attaches bare `key = value` lines to
# whichever table was most recently opened, not to the document root.

# Title shown in the email/archive header and email subject line.
digest_name = "TODO: Your Topic Digest"

# --- Hacker News (Algolia public API, no key needed) -----------------------
# Zero or more search terms. Delete this key entirely if you don't want HN.

hn_queries = [
  # "TODO: search term",
]

# --- Plain RSS/Atom feeds ---------------------------------------------------
# Zero or more. Uncomment and repeat this block per feed. `default_category`
# is optional — set it to force every item from a feed into one category
# regardless of keyword score (useful for a feed that's already 100%
# on-topic).

# [[rss_sources]]
# name = "TODO: source name"
# url = "https://example.com/feed.xml"
# default_category = "TODO: a category key from below"

# --- arXiv (public API, no key needed) --------------------------------------
# Zero or more saved searches. See https://info.arxiv.org/help/api/index.html
# for query syntax.

# [[arxiv_sources]]
# name = "TODO: search name"
# query = 'cat:cs.XX'
# max_results = 25

# --- Categories, in display order -------------------------------------------
# `keywords` are matched case-insensitively as substrings against each
# item's title + summary. Title matches count double. Highest score wins;
# ties/no-match fall through to `general`. Add more [[categories]] blocks
# above this one for anything more specific than the catch-all — exactly
# one category must have key = "general".

[[categories]]
key = "general"
title = "General"
blurb = "TODO: what this catch-all covers."
max_items = 8
keywords = []
"""

WORKFLOW_TEMPLATE = """\
name: Daily Digest

on:
  schedule:
    # Once daily at 12:00 UTC. Change the time or frequency here — always
    # UTC, standard 5-field cron: e.g. "0 8 * * *" for 08:00 UTC,
    # "0 */6 * * *" for every 6 hours, "0 12 * * 1-5" for weekdays only.
    - cron: "0 12 * * *"
  workflow_dispatch: {{}}

permissions:
  contents: write

jobs:
  digest:
    uses: LPF9000/tech-news-digest/.github/workflows/digest-reusable.yml@{ref}
    with:
      # A repository VARIABLE is recommended (Settings > Secrets and
      # variables > Actions > Variables tab) — an email address isn't
      # sensitive, and variables show their value in the Settings UI so
      # you can double-check it. If you set DIGEST_RECIPIENT as a secret
      # instead (same page, Secrets tab), this line resolving empty is
      # fine — the secrets: block below covers that case too, and only
      # one of the two needs a value.
      recipient: ${{{{ vars.DIGEST_RECIPIENT }}}}
    secrets:
      MAIL_USERNAME: ${{{{ secrets.MAIL_USERNAME }}}}
      MAIL_PASSWORD: ${{{{ secrets.MAIL_PASSWORD }}}}
      DIGEST_RECIPIENT: ${{{{ secrets.DIGEST_RECIPIENT }}}}
"""

CI_WORKFLOW_TEMPLATE = """\
name: CI

# Runs on every push/PR to this repo: lints the workflow files, validates
# config/feeds.toml actually builds, and scans the whole repo for leaked
# secrets (API keys, tokens, credentials accidentally committed). None of
# this sends email or touches digests/state — see digest.yml for that.

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-workflows:
    name: Lint GitHub Actions workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-actionlint@v1.65.2
        with:
          fail_level: error

  validate-config:
    name: Validate config/feeds.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Build a dry run (validates schema, hits real sources)
        run: |
          uvx --from "git+https://github.com/LPF9000/tech-news-digest.git@{ref}" \\
            tech-news-digest --config config/feeds.toml \\
            --html-output /tmp/preview.html --no-write-cache --no-archive

  scan-secrets:
    name: Scan for leaked secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history, not just the latest commit
      # The gitleaks CLI (Apache-2.0) run directly via its official image,
      # not the gitleaks-action marketplace wrapper: the wrapper requires a
      # paid license for organization-owned repos, the raw CLI never does.
      # Intentionally not version-pinned, unlike everything else in this
      # workflow — a secret scanner is more useful current than
      # reproducible, the same tradeoff Dependabot/CodeQL make.
      - name: gitleaks
        run: |
          docker run --rm -v "$PWD:/repo" zricethezav/gitleaks:latest \\
            detect --source /repo --no-banner -v
"""

NEXT_STEPS = """\
All three files were created in *this* repo (the one you ran this
command in), not in tech-news-digest itself — nothing there needs
cloning or editing.

Next steps:

1. Fill in the TODOs in {config_path} — either by hand, or by handing the
   file to your AI coding agent along with a description of your topic.
   Ready-to-paste prompt:

     Fill in {config_path} for the following topic: <describe your
     topic and any sources/keywords you already know>. Follow the schema
     already in the file's comments (also documented at
     https://github.com/LPF9000/tech-news-digest/blob/main/AGENTS.md#configfeedstoml-schema).
     Then validate it builds:
       uvx --from "git+https://github.com/LPF9000/tech-news-digest.git@{ref}" \\
         tech-news-digest --config {config_path} \\
         --html-output /tmp/preview.html --no-write-cache --no-archive

2. In this repository's GitHub settings, set all three of the following
   (all required — missing any one is the most common setup mistake):
   - Settings > Secrets and variables > Actions > **Secrets** tab:
     `MAIL_USERNAME` / `MAIL_PASSWORD` (a Gmail address + an App
     Password: https://myaccount.google.com/apppasswords)
   - Who receives the email — `DIGEST_RECIPIENT`, set as EITHER a
     repository variable (Settings > Secrets and variables > Actions >
     **Variables** tab — recommended, since an email address isn't
     sensitive and this way you can see its value) OR a secret (same
     page, **Secrets** tab, alongside MAIL_USERNAME/MAIL_PASSWORD). Only
     one of the two is needed; both work.
   - Settings > Actions > General > Workflow permissions -> "Read and
     write permissions" (so the workflow can commit each day's archive)

3. Commit and push {config_path}, {workflow_path}, and {ci_path}. The
   digest workflow runs daily at 12:00 UTC, or on demand from the Actions
   tab — edit the `cron` line in {workflow_path} for a different time or
   frequency (see the comment above it). {ci_path} runs on every push/PR
   from here on: it lints workflow YAML, validates config/feeds.toml
   actually builds, and scans the repo for leaked secrets — you don't
   need to do anything further to enable it.

4. Test it now rather than waiting for the schedule — do this again any
   time you change {config_path} too, not just once. Sends a real email
   to your real inbox on demand:

     Web UI: Actions tab > Daily Digest > Run workflow > Run workflow.

     gh CLI (gh auth login once if needed):
       gh workflow run digest.yml --repo {repo_slug}

   Running this a lot? Add a shell alias (~/.zshrc or ~/.bashrc):
     alias run-digest='gh workflow run digest.yml --repo {repo_slug}'

   Green check: check your inbox and this repo's new digests/ folder.
   Red X: open the failed step's log — see
   https://github.com/LPF9000/tech-news-digest/blob/main/README.md#troubleshooting
   for the common causes (an empty recipient is by far the most common).
"""


def _detect_repo_slug(directory: Path) -> str:
    """Best-effort 'owner/repo' from the directory's git remote, for exact copy-paste commands.

    Falls back to a placeholder if there's no git remote to read (not a
    repo yet, no 'origin', not a GitHub URL) — never raises.
    """
    try:
        result = subprocess.run(
            ["git", "-C", str(directory), "remote", "get-url", "origin"],
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return "<owner>/<repo>"
    if result.returncode != 0:
        return "<owner>/<repo>"
    match = _GITHUB_REMOTE_RE.search(result.stdout.strip())
    return f"{match.group(1)}/{match.group(2)}" if match else "<owner>/<repo>"


def parse_init_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="tech-news-digest init",
        description="Scaffold config/feeds.toml and a caller workflow for a new topic repo.",
    )
    parser.add_argument(
        "directory",
        nargs="?",
        type=Path,
        default=Path(),
        help="Repo root to scaffold into (default: current directory)",
    )
    parser.add_argument(
        "--ref",
        default=DEFAULT_ENGINE_REF,
        help=f"tech-news-digest ref to pin the caller workflow to (default: {DEFAULT_ENGINE_REF})",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite files that already exist")
    return parser.parse_args(argv)


def run_init(argv: list[str] | None = None) -> int:
    args = parse_init_args(argv)

    config_path = args.directory / "config" / "feeds.toml"
    workflow_path = args.directory / ".github" / "workflows" / "digest.yml"
    ci_path = args.directory / ".github" / "workflows" / "ci.yml"

    if not args.force:
        existing = [str(p) for p in (config_path, workflow_path, ci_path) if p.exists()]
        if existing:
            print(
                f"error: already exists: {', '.join(existing)} (pass --force to overwrite)",
                file=sys.stderr,
            )
            return 1

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(CONFIG_TEMPLATE, encoding="utf-8")

    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(WORKFLOW_TEMPLATE.format(ref=args.ref), encoding="utf-8")

    ci_path.parent.mkdir(parents=True, exist_ok=True)
    ci_path.write_text(CI_WORKFLOW_TEMPLATE.format(ref=args.ref), encoding="utf-8")

    print(f"Created {config_path}")
    print(f"Created {workflow_path}")
    print(f"Created {ci_path}")
    print()
    repo_slug = _detect_repo_slug(args.directory)
    print(
        NEXT_STEPS.format(
            config_path=config_path,
            workflow_path=workflow_path,
            ci_path=ci_path,
            ref=args.ref,
            repo_slug=repo_slug,
        )
    )
    return 0
