"""`tech-news-digest init`: scaffold a new topic repo's config + caller workflow.

Run this *inside the repo you want the digest to live in* — typically via
`uvx --from "git+https://github.com/LPF9000/tech-news-digest.git@<ref>"
tech-news-digest init`, so nothing needs installing locally. It writes
`config/feeds.toml` and `.github/workflows/digest.yml` with the caller
workflow already pointed at the right engine repo and ref; only the topic
content (sources/categories/keywords) is left as placeholders for a human
or an AI agent to fill in.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Keep in sync with digest-reusable.yml's own `inputs.digest-ref.default`.
DEFAULT_ENGINE_REF = "v2.0.0"

CONFIG_TEMPLATE = """\
# Source & topic configuration for your digest.
# Generated by `tech-news-digest init` — fill in the TODOs below, or hand
# this whole file plus a description of your topic to your AI coding
# agent (see the schema reference this command printed, also in
# https://github.com/LPF9000/tech-news-digest/blob/main/AGENTS.md).

# --- Top-level settings ---------------------------------------------------
# NOTE: top-level keys like these must stay above the first `[[...]]`
# array-of-tables header below — TOML attaches bare `key = value` lines to
# whichever table was most recently opened, not to the document root.

# Title shown in the email/archive header and email subject line.
digest_name = "TODO: Your Topic Digest"

# --- Hacker News (Algolia public API, no key needed) -----------------------
# Zero or more search terms. Delete this key entirely if you don't want HN.

hn_queries = [
  # "TODO: search term",
]

# --- Plain RSS/Atom feeds ---------------------------------------------------
# Zero or more. Uncomment and repeat this block per feed. `default_category`
# is optional — set it to force every item from a feed into one category
# regardless of keyword score (useful for a feed that's already 100%
# on-topic).

# [[rss_sources]]
# name = "TODO: source name"
# url = "https://example.com/feed.xml"
# default_category = "TODO: a category key from below"

# --- arXiv (public API, no key needed) --------------------------------------
# Zero or more saved searches. See https://info.arxiv.org/help/api/index.html
# for query syntax.

# [[arxiv_sources]]
# name = "TODO: search name"
# query = 'cat:cs.XX'
# max_results = 25

# --- Categories, in display order -------------------------------------------
# `keywords` are matched case-insensitively as substrings against each
# item's title + summary. Title matches count double. Highest score wins;
# ties/no-match fall through to `general`. Add more [[categories]] blocks
# above this one for anything more specific than the catch-all — exactly
# one category must have key = "general".

[[categories]]
key = "general"
title = "General"
blurb = "TODO: what this catch-all covers."
max_items = 8
keywords = []
"""

WORKFLOW_TEMPLATE = """\
name: Daily Digest

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: {{}}

permissions:
  contents: write

jobs:
  digest:
    uses: LPF9000/tech-news-digest/.github/workflows/digest-reusable.yml@{ref}
    with:
      recipient: ${{{{ vars.DIGEST_RECIPIENT }}}}
    secrets:
      MAIL_USERNAME: ${{{{ secrets.MAIL_USERNAME }}}}
      MAIL_PASSWORD: ${{{{ secrets.MAIL_PASSWORD }}}}
"""

NEXT_STEPS = """\
Next steps:

1. Fill in the TODOs in {config_path} — either by hand, or by handing the
   file to your AI coding agent along with a description of your topic.
   Ready-to-paste prompt:

     Fill in {config_path} for the following topic: <describe your
     topic and any sources/keywords you already know>. Follow the schema
     already in the file's comments (also documented at
     https://github.com/LPF9000/tech-news-digest/blob/main/AGENTS.md#configfeedstoml-schema).
     Then validate it builds:
       uvx --from "git+https://github.com/LPF9000/tech-news-digest.git@{ref}" \\
         tech-news-digest --config {config_path} \\
         --html-output /tmp/preview.html --no-write-cache --no-archive

2. In this repository's GitHub settings, set:
   - Secrets `MAIL_USERNAME` / `MAIL_PASSWORD` (a Gmail address + an App
     Password: https://myaccount.google.com/apppasswords)
   - Variable `DIGEST_RECIPIENT` (who receives the email)
   - Settings > Actions > General > Workflow permissions -> "Read and
     write permissions" (so the workflow can commit each day's archive)

3. Commit and push {config_path} and {workflow_path}. The workflow runs
   daily at 12:00 UTC, or on demand from the Actions tab.
"""


def parse_init_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="tech-news-digest init",
        description="Scaffold config/feeds.toml and a caller workflow for a new topic repo.",
    )
    parser.add_argument(
        "directory",
        nargs="?",
        type=Path,
        default=Path(),
        help="Repo root to scaffold into (default: current directory)",
    )
    parser.add_argument(
        "--ref",
        default=DEFAULT_ENGINE_REF,
        help=f"tech-news-digest ref to pin the caller workflow to (default: {DEFAULT_ENGINE_REF})",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite files that already exist")
    return parser.parse_args(argv)


def run_init(argv: list[str] | None = None) -> int:
    args = parse_init_args(argv)

    config_path = args.directory / "config" / "feeds.toml"
    workflow_path = args.directory / ".github" / "workflows" / "digest.yml"

    if not args.force:
        existing = [str(p) for p in (config_path, workflow_path) if p.exists()]
        if existing:
            print(
                f"error: already exists: {', '.join(existing)} (pass --force to overwrite)",
                file=sys.stderr,
            )
            return 1

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(CONFIG_TEMPLATE, encoding="utf-8")

    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(WORKFLOW_TEMPLATE.format(ref=args.ref), encoding="utf-8")

    print(f"Created {config_path}")
    print(f"Created {workflow_path}")
    print()
    print(NEXT_STEPS.format(config_path=config_path, workflow_path=workflow_path, ref=args.ref))
    return 0
